# This is a basic workflow to help you get started with Actions

name: Blog Pages Upload Tencent AOS

on:
  # Runs on pushes targeting the default branch
#   push:
#     paths: 
#       - 'site/**'
#   workflow_run:
#     workflows: ["Daily Bing Image Update"]
#     types:
#       - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      working-directory: ./site
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true # Checkout private submodules(themes or something else).
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm ci
        working-directory: ${{ env.working-directory }}
      - name: Build
        run: npm run build
        working-directory: ${{ env.working-directory }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: blog-build-result
          path: ./site/public
          retention-days: 5
          
  aos-deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: 检出仓库代码
      uses: actions/checkout@master
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: blog-build-result
    - name: Display structure of downloaded files
      run: ls -R
    - name: 安装腾讯云依赖
      run: |
        sudo pip install coscmd
        sudo pip install tccli

    - name: 配置腾讯云依赖
      env:
        SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
        SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
        BUCKET: github-blog-1302453266 #改为自己的存储桶名称
        REGION: ap-chengdu #改为自己的地域
      run: |
        coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
        tccli configure set secretId $SECRET_ID
        tccli configure set secretKey $SECRET_KEY
        tccli configure set region $REGION

    - name: 上传到腾讯云COS并刷新CDN
      run: |
        coscmd upload -rfs --delete ./ /
